# Generated by Django 4.2.1 on 2023-05-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='Form',
        ),
    ]
