# Generated by Django 4.2.1 on 2023-05-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_rename_bank_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='MyForm',
        ),
    ]
